Re-add .NET Standard 2.0 to framework targets…
sillsdev/flexbridge pull request #372
Opened 2022-08-01 18:48 UTC by papeh

…for the projects used by LFMerge.

Also reference Win32.Registry in LibTriboroughBridge-ChorusPlugin to fix a pretty ugly build warning about version conflicts.

This reverts commit d00ed11f584e81ebf8f2c2fe7670bd7f83114180.

2022-08-22 09:25 UTC, josephmyers commented
Without having looked at this a ton, my understanding is this is blocked until we get [the Chorus PR](https://github.com/sillsdev/chorus/pull/279) in.

2022-08-25 09:25 UTC, josephmyers commented
This is unblocked now

2022-08-26 08:54 UTC, ermshiperete requested changes
This should have an entry in the Added section of `CHANGELOG.md` and a `+semver:minor` in the commit message.

2022-08-26 09:32 UTC, ermshiperete approved these changes
Are you planning on creating a 3.6.4 release today? Otherwise don't create the 3.6.4 section head but leave it under Unreleased.

2022-08-26 09:49 UTC, josephmyers commented
Oh got it

2022-08-26 11:24 UTC, ermshiperete approved these changes

2022-08-29 21:54 UTC, papeh reviewed
For some reason, TeamCity jobs ([Windows](https://build.palaso.org/buildConfiguration/FLExBridge_FLExBridgeDevelopWin32Continuous) and [Linux](https://build.palaso.org/buildConfiguration/FLExBridgeDevelopLinux64Continuous)) are unable to see this PR. Strange that problem seems to be consistent for and peculiar to .NET Standard PR's. Since we still use TeamCity for Windows release builds, I hope we can get this straightened out.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/372#-:-NAf_Rsh9rf3EeCwmkrH:b-7ibe1x)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2022-08-30 07:31 UTC, merged

2022-08-30 07:39 UTC, josephmyers commented
I see that the builds still run on develop. I can test that the bug is present by opening a new branch and PR, but I don't have the ability to do much on the TC configuration side.